In [3]:
import numpy as np

In [6]:
##                 start end difference
array1 = np.arange(1,2,0.5)
array1

array([1. , 1.5])

In [7]:
##                  start end number_of_items_with_equal_difference
array1 = np.linspace(1,2,5)
array1

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [8]:
array1 = np.arange(1,20)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [9]:
array1[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [17]:
array1[:6:2]  # [start end step]

array([1, 3, 5])

In [19]:
array1[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1])

## Multi dim array slicing:

### 2D ARRAY:

In [34]:
array2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])


In [23]:
array2[0][2]

3

In [24]:
array2[0,2]

3

In [27]:
array2[0:3,2] # each row in the 3rd column

array([3, 6, 9])

In [29]:
array2[1,0:3] # ecah column in the 2nd row

array([4, 5, 6])

In [31]:
array2[1:3,:] # 2nd and 3rd row each column

array([[4, 5, 6],
       [7, 8, 9]])

In [33]:
array2[1,:] # 2nd row each column

array([4, 5, 6])

### 3D ARRAY:

In [43]:
array1 = np.arange(1,28)
array2 = np.reshape(array1, newshape=(3,3,3),order='C')
array2

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [44]:
array2[0][0][0]

1

In [46]:
array2[0,:,:] 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
array2[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
array2[0,...] # 1st row all y & z values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
array2[...,1] # all x y x only 2nd columns

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [51]:
array2[1,...] # second row's all y & z values

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [54]:
array2[1,:,:]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [58]:
arr = np.arange(1,82)
array3 = np.reshape(arr,newshape=(3,3,3,3))
array3

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]],


       [[[28, 29, 30],
         [31, 32, 33],
         [34, 35, 36]],

        [[37, 38, 39],
         [40, 41, 42],
         [43, 44, 45]],

        [[46, 47, 48],
         [49, 50, 51],
         [52, 53, 54]]],


       [[[55, 56, 57],
         [58, 59, 60],
         [61, 62, 63]],

        [[64, 65, 66],
         [67, 68, 69],
         [70, 71, 72]],

        [[73, 74, 75],
         [76, 77, 78],
         [79, 80, 81]]]])

In [62]:
array3[1,...]  # is equivalent to array3[1,:,:,:]

array([[[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[37, 38, 39],
        [40, 41, 42],
        [43, 44, 45]],

       [[46, 47, 48],
        [49, 50, 51],
        [52, 53, 54]]])

In [65]:
for row in array3:
    print(row[2])

[[19 20 21]
 [22 23 24]
 [25 26 27]]
[[46 47 48]
 [49 50 51]
 [52 53 54]]
[[73 74 75]
 [76 77 78]
 [79 80 81]]


## Conversion of String to Numeric:

In [13]:
from io import StringIO

In [17]:
data = u"1, 2, 3, 4, 5, 6\n7, 8, 9, 10, 11, 12\n13, 14, 15, 16 ,17 ,18"
np.genfromtxt(StringIO(data), delimiter=",")

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.],
       [13., 14., 15., 16., 17., 18.]])

## Random Number:

In [18]:
array1 = np.random.rand(3,3,3)  # generate random number between 0 and 1

array([[[0.49913921, 0.03623841, 0.68763972],
        [0.90614616, 0.78542624, 0.23996363],
        [0.04741028, 0.15908088, 0.00884478]],

       [[0.74800734, 0.61790448, 0.0732708 ],
        [0.19327683, 0.859272  , 0.79267063],
        [0.21960363, 0.00349043, 0.8112839 ]],

       [[0.36438467, 0.68866386, 0.21275378],
        [0.60013081, 0.11466405, 0.36099348],
        [0.45443006, 0.17361512, 0.57308156]]])

In [23]:
array2 = np.random.randint(10,100,10) #(lowest number , highest num(optional) , size , dtype) generate integer random number 
array2 

array([53, 71, 21, 92, 74, 80, 85, 31, 67, 79])

## Boolean Operations:
- **in1d** <br>
- **intersect1d** <br>
- **isin** <br>
- **setdiff1d** <br>
- **setxor1d** <br>
- **union1d** <br>

In [32]:
# Tickets id's in our system:
ticketsData = "330911,363272,240276,315154,3101298,7538,330972,248738,2657"
tickets = np.genfromtxt(StringIO(ticketsData),delimiter=",")
#Tickets id's given by Gov to check either they are in our system or not
GovticketsData ="330911,575368,240276,567546,2344567,7538,330972,248738,986868"
govtickets = np.genfromtxt(StringIO(GovticketsData),delimiter=",")

available = tickets[[np.in1d(tickets,govtickets)]]
print("These tickets are present in our dataset:")
for i in available:
    print(i)

These tickets are present in our dataset:
330911.0
240276.0
7538.0
330972.0
248738.0


C:\Users\Windows\AppData\Local\Temp\ipykernel_11092\469691678.py:8: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  available = tickets[[np.in1d(tickets,govtickets)]]


In [33]:
tickets = np.genfromtxt(StringIO(ticketsData),delimiter=",")
govtickets = np.genfromtxt(StringIO(GovticketsData),delimiter=",")

available = np.intersect1d(tickets,govtickets)
available

array([  7538., 240276., 248738., 330911., 330972.])

In [35]:
tickets = np.genfromtxt(StringIO(ticketsData),delimiter=",")
govtickets = np.genfromtxt(StringIO(GovticketsData),delimiter=",")

available = np.isin(tickets,govtickets)
tickets[available]

array([330911., 240276.,   7538., 330972., 248738.])

In [37]:
tickets = np.genfromtxt(StringIO(ticketsData),delimiter=",")
govtickets = np.genfromtxt(StringIO(GovticketsData),delimiter=",")

available = np.setdiff1d(tickets,govtickets) 
available

array([2.657000e+03, 3.151540e+05, 3.632720e+05, 3.101298e+06])

In [38]:
tickets = np.genfromtxt(StringIO(ticketsData),delimiter=",")
govtickets = np.genfromtxt(StringIO(GovticketsData),delimiter=",")

available = np.setxor1d(tickets,govtickets)
available

array([2.657000e+03, 3.151540e+05, 3.632720e+05, 5.675460e+05,
       5.753680e+05, 9.868680e+05, 2.344567e+06, 3.101298e+06])

In [40]:
tickets = np.genfromtxt(StringIO(ticketsData),delimiter=",")
govtickets = np.genfromtxt(StringIO(GovticketsData),delimiter=",")

available = np.union1d(tickets,govtickets)
available

array([2.657000e+03, 7.538000e+03, 2.402760e+05, 2.487380e+05,
       3.151540e+05, 3.309110e+05, 3.309720e+05, 3.632720e+05,
       5.675460e+05, 5.753680e+05, 9.868680e+05, 2.344567e+06,
       3.101298e+06])