In [2]:
import numpy as np

# Basic array operations:

In [3]:
# add respective elements of two arrays:
data1 = np.array([1,3,4,5,6])
data2 = np.ones(5,dtype=int)
data1+data2

array([2, 4, 5, 6, 7])

# Broadcasting:

```when we want to carryout operation between a single value(scalar) and an array (also called an operation between a vector and a scalar) or between arrays of two different sizes we use broadcasting methodology```<br>

In [4]:
data1 = np.array([1,3,4,5,6])
data1*6

array([ 6, 18, 24, 30, 36])

# More useful array operations:

In [5]:
print(data1.max())
print(data1.min())
print(data1.sum())

6
1
19


In [6]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [8]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [9]:
a.min(axis=1)

array([0.17296777, 0.05093587, 0.12697628])

# Creating matrices:

In [11]:
matrix = np.array([[1,2],[3,4],[5,6]])
matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
matrix.size
matrix.shape
matrix.ndim

2

# Generating random numbers:

In [18]:
from numpy.random import default_rng
rng = default_rng()
vals = rng.standard_normal(10)
more_vals = rng.standard_normal(10)

In [19]:
vals

array([-0.49694515,  0.61600937, -0.77814185, -0.15542642, -0.00111032,
        0.19894898,  0.33138266, -0.03771488, -0.60977665, -0.05595024])

In [20]:
more_vals

array([-0.74276057,  2.0725138 , -0.62990119,  0.56894849,  0.68764313,
       -0.22721   , -0.57574257,  0.20753625,  0.4972276 , -0.49579232])

# Get unique items and counts

In [21]:
array1=np.array([12,12,23,43,34,54,43,23])
print(np.unique(array1))

[12 23 34 43 54]


In [22]:
array1=np.array([12,12,23,43,34,54,43,23])
print(np.unique(array1,return_index=True))

(array([12, 23, 34, 43, 54]), array([0, 2, 4, 3, 5], dtype=int64))


In [23]:
array1=np.array([12,12,23,43,34,54,43,23])
print(np.unique(array1,return_counts=True))

(array([12, 23, 34, 43, 54]), array([2, 2, 1, 2, 1], dtype=int64))


# Transponse :

In [24]:
matrix.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

# Reverse an array

Reversing a 1D array:

In [25]:
array1 = np.array([0,1,2,3,4,5,6])
reversed_array1 = np.flip(array1)
print("1D array -->",array1)
print("1D Reversed_array -->",reversed_array1)

1D array --> [0 1 2 3 4 5 6]
1D Reversed_array --> [6 5 4 3 2 1 0]


Reversing a 2D array:

In [26]:
array2 = np.array([[1,2],[3,4],[5,6]])
reversed_array2 = np.flip(array2)
print("1D array -->",array2)
print("1D Reversed_array -->",reversed_array2)

1D array --> [[1 2]
 [3 4]
 [5 6]]
1D Reversed_array --> [[6 5]
 [4 3]
 [2 1]]


In [29]:
array2 = np.array([[1,2],[3,4],[5,6]])
reversed_array2 = np.flip(array2,axis=0)
print("1D array -->",array2)
print("1D Reversed_array -->",reversed_array2)

1D array --> [[1 2]
 [3 4]
 [5 6]]
1D Reversed_array --> [[5 6]
 [3 4]
 [1 2]]


In [30]:
array2 = np.array([[1,2],[3,4],[5,6]])
reversed_array2 = np.flip(array2,axis=1)
print("1D array -->",array2)
print("1D Reversed_array -->",reversed_array2)

1D array --> [[1 2]
 [3 4]
 [5 6]]
1D Reversed_array --> [[2 1]
 [4 3]
 [6 5]]


# Reshaping and flattening multidimensional arrays:

```There are two ways to make an array flatten```<br>
- ```.flatten()```<br>
- ```.ravel()```<br>
```the main difference between flatten & ravel is that .flatten() is works on the phenomenon of Deep copy while .ravel() works on the phenomenon of Shallow copy ```

In [42]:
array1 = np.array([[1,2,7],[3,4,8],[5,6,9]])
array2 = array1.flatten()


In [43]:
array1[0]=[4,5,6]

In [45]:
array1

array([[4, 5, 6],
       [3, 4, 8],
       [5, 6, 9]])

In [46]:
array2 ## deep copy

array([1, 2, 7, 3, 4, 8, 5, 6, 9])

In [37]:
array1 = np.array([[1,2,7],[3,4,8],[5,6,9]])
array2 = array1.ravel()

In [38]:
array1[0]=[4,5,6]

In [39]:
array1

array([[4, 5, 6],
       [3, 4, 8],
       [5, 6, 9]])

In [40]:
array2 ##shallow copy

array([4, 5, 6, 3, 4, 8, 5, 6, 9])