In [1]:
!pip install Numpy

In [2]:
import numpy as np

In [9]:
np.__version__ 

'1.21.5'

#  NUMPY ARRAYS:

-  ``` An array is a central data structure of the NumPy library ```<br>
- ``` Central data structure means a data repository which is responsible for providing permanent data storage ``` <br>
-  ``` An array is a grid of values and it contains information about the raw data ```<br>
- ``` The elements of an array are all of the same data type ``` <br>
-  ``` An array can be indexed by a tuple of nonnegative integers, by booleans, by another array, or by integers.  ```<br>
-  <b>```rank```</b>```the number of dimensions of an array ``` <br>
-  <b>```shape```</b>```The shape of the array is a tuple of integers giving the size of the array along each dimension.``` <br>
-  <b>```ndarray```</b>```An N-dimensional array is simply an array with any number of dimensions. 1-D,2-D etc``` <br>
-  <b>```vector```</b>```A vector is an array with a single dimension ``` <br>
-  <b>```matrix```</b>```a matrix refers to an array with two dimensions.``` <br>
-  <b>```tensor```</b>``` 3-D or higher dimensional arrays``` <br>

##  ATTRIBUTES OF NUMPY ARRAYS:

-  ``` An array is usually a fixed-size container of items of the same type and size.  ```<br>
-  ``` The number of dimensions and items in an array is defined by its shape. ```<br>
-  ``` Dimensions are called axes. ```<br>

## FUNCTIONS FOR INITIALIZATION OF  AN ARRAY:

-  <b>```np.array()```</b>```To create a NumPy array, we can use the function np.array(). ``` <br>
-  <b>```np.zeros()```</b>```To create a NumPy array filled with zeros, we can use the function np.zeros().``` <br>
-  <b>```np.ones()```</b>``` To create a NumPy array filled with zeros, we can use the function np.ones().``` <br>
-  <b>```np.empty()```</b>```The function empty creates an array whose initial content is random and depends on the state of the memory.  ``` <br>
-  <b>```np.arange()```</b>```We can create an array with a range of elements.``` <br>
-  <b>```np.linspace()```</b>```You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval``` <br>

### np.array()

In [14]:
a = np.array([1,2,3,4,5]) # creating an array using python list
print(a)
b = np.array([[1,2,3,4,5],[6,7,8,9,10]]) # creating an array using python list of list
print(b)

[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### np.zeros()

In [17]:
a = np.zeros(2)
print(a)
a = np.zeros(4)
print(a)

[0. 0.]
[0. 0. 0. 0.]


### np.ones()

In [21]:
a = np.ones(7)
print(a)
a = np.ones(4)
print(a)

[1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1.]


### np.empty()

In [23]:
c = np.empty(7)
print(c)
c = np.empty(4)
print(c)

[1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1.]


### np.linspace()


In [24]:
d = np.linspace(0,10, num=5)  # generate array of 5 elements with equal difference 
print(d)

[ 0.   2.5  5.   7.5 10. ]


### Specifying your data type:


In [25]:
e = np.ones(5,dtype=np.int64)
e

array([1, 1, 1, 1, 1], dtype=int64)

## ADDING, REMOVING, SORTING:

In [4]:
array1 = np.array([2,4,1,9,5,3,0,2,1])
sorted_array1 = np.sort(array1)
sorted_array1

array([0, 1, 1, 2, 2, 3, 4, 5, 9])

In [8]:
array2 = np.array([[7,2,5],[1,4,3]])
sorted_array2 = np.sort(array2) # sort along the last axis OR row wise sorting
sorted_array2

array([[2, 5, 7],
       [1, 3, 4]])

In [10]:
array3 = np.array([[7,2,5],[1,4,3]])
sorted_array3 = np.sort(array3,axis=None) # sort the flattened array OR sorting array in one dimension
sorted_array3

array([1, 2, 3, 4, 5, 7])

In [13]:
array4 = np.array([[7,2,5],[1,4,3]])
sorted_array4 = np.sort(array4 , axis = 0)  # sort along the first axis OR column wise sorting
sorted_array4

array([[1, 2, 3],
       [7, 4, 5]])

```There are 4 types of additional sortings in Numpy on an array:```<br>
- ```argsort```<br>
- ```lexsort```<br>
- ```searchsort```<br>
- ```partioningsort```<br>



### np.concatenate()

In [15]:
array1 = np.array([1,3,5,7,9])
array2 = np.array([2,4,6,8,10])
concatinated_array = np.concatenate((array1,array2))
concatinated_array

array([ 1,  3,  5,  7,  9,  2,  4,  6,  8, 10])

In [20]:
array1 = np.array([[1,3,5,7,9]])
array2 = np.array([[2,4,6,8,10],[11,13,15,17,19]])
concatinated_array = np.concatenate((array1,array2),axis=0)
concatinated_array

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10],
       [11, 13, 15, 17, 19]])

### np.delete(array,index)

In [21]:
array1 = np.array([1,2,3,4,5,6,7,8,9])
np.delete(array1,8)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
index = [2, 3, 6]

new_a = np.delete(a, index)

print(new_a)

[1 2 5 6 8 9]


-  <b>```ndarray.ndim()```</b>```It tells us the axes and dimensions of an array. ``` <br>
-  <b>```ndarray.size()```</b>```It tells us the total elements in an array.``` <br>
-  <b>```ndarray.shape()```</b>```It tells the no. of rows and columns in an array.``` <br>

In [23]:
array1 = np.array(
    [[[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]]
)
array1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [24]:
array1.ndim

3

In [25]:
array1.size

18

In [26]:
array1.shape

(3, 2, 3)

``` we can reshape an array by using ndarray.reshape()```<br>
```ndarray.reshape()```<br>
<b>```reshape(arrayName , newshape=(rows,columns) , order='C OR F OR A' )```</b><br>
<b>```C```</b>```means to read/write the elements using C-like index order```<br>
<b>```F```</b>``` means to read/write the elements using Fortran-like index order```<br>
<b>```A```</b>``` means to read/write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise.```<br>

### np.reshape():

In [27]:
array1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [30]:
np.reshape(array1,newshape=(9,2,1),order='C')

array([[[ 1],
        [ 2]],

       [[ 3],
        [ 4]],

       [[ 5],
        [ 6]],

       [[ 7],
        [ 8]],

       [[ 9],
        [10]],

       [[11],
        [12]],

       [[13],
        [14]],

       [[15],
        [16]],

       [[17],
        [18]]])

## How to convert a 1D array into a 2D array (how to add a new axis to an array): 
- ```[np.newaxis,:]```
- ```[:,np.newaxis]```
- ```np.expand_dims()```

In [33]:
a = np.arange(0,10)# it have 10 rows and no column
a.shape

(10,)

In [43]:
a2 = a[np.newaxis,:] # row vector
a3 = a[:,np.newaxis] # column vector
print(a2,"\n",a3)

[[0 1 2 3 4 5 6 7 8 9]] 
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


### np.expand_dims():

In [47]:
a = np.arange(0,10)# it have 10 rows and no column
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
b = np.expand_dims(a,axis=0) # row vector
b                          

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [49]:
b = np.expand_dims(a,axis=1) # column vector
b

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

## INDEXING and SLICING:

In [53]:
array1 = np.array([1,4,2,8,3,6])
array1[0]
array1[-1]
array1[2:]
array1[:2]

array([1, 4])

In [54]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array1[array1>4])

[5 6 7 8 9]


## How to create an array from existing data:

### using slicing method:

In [55]:
array1 = np.array([1,3,2,4,2,5,3,2,5,7,6])
# we can create new array from existing array using slicling

array2 = array1[2:]
array2

array([2, 4, 2, 5, 3, 2, 5, 7, 6])

### using stack arrays method:

In [ ]:
# we can creating new array by stacking two or more existing arrays:

array1=np.array([[1,2,3],
                 [4,5,6]])
array2=np.array([[7,8,9],
              [10,11,12]])

In [71]:
np.vstack((array1,array2)) # stacked vertically

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [72]:
np.hstack((array1,array2)) # stacked horizontally

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### using split array method:

In [74]:
a = np.arange(1,65).reshape(8,8)
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [75]:
h= np.hsplit(a,4)#splits an array horizontally in 4 arrays
h

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26],
        [33, 34],
        [41, 42],
        [49, 50],
        [57, 58]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28],
        [35, 36],
        [43, 44],
        [51, 52],
        [59, 60]]),
 array([[ 5,  6],
        [13, 14],
        [21, 22],
        [29, 30],
        [37, 38],
        [45, 46],
        [53, 54],
        [61, 62]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24],
        [31, 32],
        [39, 40],
        [47, 48],
        [55, 56],
        [63, 64]])]

In [76]:
v= np.vsplit(a,4)#splits an array vertically in 4 arrays
v

[array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16]]),
 array([[17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32]]),
 array([[33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48]]),
 array([[49, 50, 51, 52, 53, 54, 55, 56],
        [57, 58, 59, 60, 61, 62, 63, 64]])]